import type { ItemLocation } from "../schemas";

export const ITEM_LOCATIONS: ItemLocation[] = ["pantry", "fridge", "freezer"];

export const FOOD_CATEGORIES = [
  "Dairy",
  "Meat & Poultry",
  "Seafood",
  "Produce",
  "Bread & Bakery",
  "Breakfast & Cereal",
  "Grains & Pasta",
  "Baking",
  "Canned Goods",
  "Condiments & Sauces",
  "Oils & Vinegars",
  "Snacks",
  "Beverages",
  "Frozen Foods",
  "Spices & Seasonings",
  "Other",
] as const;

export const COMMON_UNITS = [
  "unit",
  "lb",
  "oz",
  "fl oz",
  "kg",
  "g",
  "gal",
  "qt",
  "pt",
  "cup",
  "L",
  "mL",
  "dozen",
  "bunch",
  "can",
  "jar",
  "box",
  "bag",
  "package",
] as const;

export const API_ENDPOINTS = {
  HEALTH: "/health",
  ITEMS: "/items",
  HOUSEHOLDS: "/households",
  BARCODE: "/barcode",
  RECEIPT: "/receipt",
  SHOPPING_LIST: "/shopping-list",
} as const;

export interface ItemPreset {
  name: string;
  category: string;
  unit: string;
  estimatedShelfDays: number;
}

export const ITEM_PRESETS: ReadonlyArray<ItemPreset> = [
  // --- Produce (60 items) ---
  { name: "Apple", category: "Produce", unit: "lb", estimatedShelfDays: 30 },
  { name: "Asparagus", category: "Produce", unit: "lb", estimatedShelfDays: 4 },
  { name: "Artichoke", category: "Produce", unit: "unit", estimatedShelfDays: 7 },
  { name: "Avocado", category: "Produce", unit: "unit", estimatedShelfDays: 5 },
  { name: "Banana", category: "Produce", unit: "lb", estimatedShelfDays: 7 },
  { name: "Beet", category: "Produce", unit: "lb", estimatedShelfDays: 14 },
  { name: "Bell Pepper", category: "Produce", unit: "unit", estimatedShelfDays: 10 },
  { name: "Blueberries", category: "Produce", unit: "oz", estimatedShelfDays: 10 },
  { name: "Broccoli", category: "Produce", unit: "lb", estimatedShelfDays: 7 },
  { name: "Brussels Sprouts", category: "Produce", unit: "lb", estimatedShelfDays: 7 },
  { name: "Cabbage", category: "Produce", unit: "unit", estimatedShelfDays: 14 },
  { name: "Carrot", category: "Produce", unit: "lb", estimatedShelfDays: 21 },
  { name: "Cauliflower", category: "Produce", unit: "unit", estimatedShelfDays: 14 },
  { name: "Celery", category: "Produce", unit: "unit", estimatedShelfDays: 14 },
  { name: "Cherry", category: "Produce", unit: "lb", estimatedShelfDays: 7 },
  { name: "Corn", category: "Produce", unit: "unit", estimatedShelfDays: 3 },
  { name: "Cucumber", category: "Produce", unit: "unit", estimatedShelfDays: 7 },
  { name: "Eggplant", category: "Produce", unit: "unit", estimatedShelfDays: 7 },
  { name: "Fennel", category: "Produce", unit: "unit", estimatedShelfDays: 7 },
  { name: "Fresh Basil", category: "Produce", unit: "oz", estimatedShelfDays: 7 },
  { name: "Fresh Cilantro", category: "Produce", unit: "bunch", estimatedShelfDays: 7 },
  { name: "Fresh Dill", category: "Produce", unit: "bunch", estimatedShelfDays: 7 },
  { name: "Fresh Parsley", category: "Produce", unit: "bunch", estimatedShelfDays: 7 },
  { name: "Fresh Rosemary", category: "Produce", unit: "bunch", estimatedShelfDays: 14 },
  { name: "Fresh Thyme", category: "Produce", unit: "bunch", estimatedShelfDays: 7 },
  { name: "Garlic", category: "Produce", unit: "unit", estimatedShelfDays: 90 },
  { name: "Ginger Root", category: "Produce", unit: "oz", estimatedShelfDays: 21 },
  { name: "Grape", category: "Produce", unit: "lb", estimatedShelfDays: 10 },
  { name: "Grapefruit", category: "Produce", unit: "unit", estimatedShelfDays: 21 },
  { name: "Green Beans", category: "Produce", unit: "lb", estimatedShelfDays: 7 },
  { name: "Jalapeño", category: "Produce", unit: "unit", estimatedShelfDays: 14 },
  { name: "Kale", category: "Produce", unit: "bunch", estimatedShelfDays: 7 },
  { name: "Kiwi", category: "Produce", unit: "unit", estimatedShelfDays: 7 },
  { name: "Leek", category: "Produce", unit: "unit", estimatedShelfDays: 14 },
  { name: "Lemon", category: "Produce", unit: "unit", estimatedShelfDays: 21 },
  { name: "Lettuce", category: "Produce", unit: "unit", estimatedShelfDays: 7 },
  { name: "Lime", category: "Produce", unit: "unit", estimatedShelfDays: 21 },
  { name: "Mango", category: "Produce", unit: "unit", estimatedShelfDays: 5 },
  { name: "Mushroom", category: "Produce", unit: "oz", estimatedShelfDays: 7 },
  { name: "Onion", category: "Produce", unit: "lb", estimatedShelfDays: 30 },
  { name: "Orange", category: "Produce", unit: "lb", estimatedShelfDays: 21 },
  { name: "Peach", category: "Produce", unit: "unit", estimatedShelfDays: 5 },
  { name: "Pear", category: "Produce", unit: "unit", estimatedShelfDays: 7 },
  { name: "Pineapple", category: "Produce", unit: "unit", estimatedShelfDays: 5 },
  { name: "Plum", category: "Produce", unit: "lb", estimatedShelfDays: 5 },
  { name: "Potato", category: "Produce", unit: "lb", estimatedShelfDays: 30 },
  { name: "Radish", category: "Produce", unit: "bunch", estimatedShelfDays: 7 },
  { name: "Raspberry", category: "Produce", unit: "oz", estimatedShelfDays: 5 },
  { name: "Romaine Lettuce", category: "Produce", unit: "unit", estimatedShelfDays: 7 },
  { name: "Scallion", category: "Produce", unit: "bunch", estimatedShelfDays: 7 },
  { name: "Shallot", category: "Produce", unit: "unit", estimatedShelfDays: 30 },
  { name: "Snap Peas", category: "Produce", unit: "lb", estimatedShelfDays: 5 },
  { name: "Spinach", category: "Produce", unit: "oz", estimatedShelfDays: 7 },
  { name: "Strawberry", category: "Produce", unit: "lb", estimatedShelfDays: 5 },
  { name: "Sweet Potato", category: "Produce", unit: "lb", estimatedShelfDays: 21 },
  { name: "Swiss Chard", category: "Produce", unit: "bunch", estimatedShelfDays: 5 },
  { name: "Tomato", category: "Produce", unit: "lb", estimatedShelfDays: 7 },
  { name: "Turnip", category: "Produce", unit: "lb", estimatedShelfDays: 14 },
  { name: "Watermelon", category: "Produce", unit: "unit", estimatedShelfDays: 7 },
  { name: "Zucchini", category: "Produce", unit: "unit", estimatedShelfDays: 7 },
  // --- Meat & Poultry (18 items) ---
  { name: "Bacon", category: "Meat & Poultry", unit: "lb", estimatedShelfDays: 7 },
  { name: "Beef Brisket", category: "Meat & Poultry", unit: "lb", estimatedShelfDays: 3 },
  { name: "Beef Steak", category: "Meat & Poultry", unit: "lb", estimatedShelfDays: 3 },
  { name: "Chicken Breast", category: "Meat & Poultry", unit: "lb", estimatedShelfDays: 3 },
  { name: "Chicken Thighs", category: "Meat & Poultry", unit: "lb", estimatedShelfDays: 3 },
  { name: "Chicken Wings", category: "Meat & Poultry", unit: "lb", estimatedShelfDays: 3 },
  { name: "Ground Beef", category: "Meat & Poultry", unit: "lb", estimatedShelfDays: 2 },
  { name: "Ground Turkey", category: "Meat & Poultry", unit: "lb", estimatedShelfDays: 2 },
  { name: "Hot Dogs", category: "Meat & Poultry", unit: "unit", estimatedShelfDays: 7 },
  { name: "Lamb Chop", category: "Meat & Poultry", unit: "lb", estimatedShelfDays: 3 },
  { name: "Pepperoni", category: "Meat & Poultry", unit: "oz", estimatedShelfDays: 14 },
  { name: "Pork Chop", category: "Meat & Poultry", unit: "lb", estimatedShelfDays: 3 },
  { name: "Pork Tenderloin", category: "Meat & Poultry", unit: "lb", estimatedShelfDays: 3 },
  { name: "Salami", category: "Meat & Poultry", unit: "oz", estimatedShelfDays: 14 },
  { name: "Sausage Links", category: "Meat & Poultry", unit: "lb", estimatedShelfDays: 5 },
  { name: "Sliced Ham", category: "Meat & Poultry", unit: "lb", estimatedShelfDays: 5 },
  { name: "Sliced Turkey", category: "Meat & Poultry", unit: "lb", estimatedShelfDays: 5 },
  { name: "Whole Chicken", category: "Meat & Poultry", unit: "lb", estimatedShelfDays: 3 },
  // --- Seafood (10 items) ---
  { name: "Cod Fillet", category: "Seafood", unit: "lb", estimatedShelfDays: 2 },
  { name: "Crab Legs", category: "Seafood", unit: "lb", estimatedShelfDays: 2 },
  { name: "Halibut", category: "Seafood", unit: "lb", estimatedShelfDays: 2 },
  { name: "Mussels", category: "Seafood", unit: "lb", estimatedShelfDays: 2 },
  { name: "Salmon Fillet", category: "Seafood", unit: "lb", estimatedShelfDays: 2 },
  { name: "Scallops", category: "Seafood", unit: "lb", estimatedShelfDays: 2 },
  { name: "Sea Bass", category: "Seafood", unit: "lb", estimatedShelfDays: 2 },
  { name: "Shrimp", category: "Seafood", unit: "lb", estimatedShelfDays: 2 },
  { name: "Tilapia", category: "Seafood", unit: "lb", estimatedShelfDays: 2 },
  { name: "Tuna Steak", category: "Seafood", unit: "lb", estimatedShelfDays: 2 },
  // --- Bread & Bakery (10 items) ---
  { name: "Bagels", category: "Bread & Bakery", unit: "unit", estimatedShelfDays: 5 },
  { name: "Baguette", category: "Bread & Bakery", unit: "unit", estimatedShelfDays: 2 },
  { name: "Croissants", category: "Bread & Bakery", unit: "unit", estimatedShelfDays: 3 },
  { name: "Dinner Rolls", category: "Bread & Bakery", unit: "unit", estimatedShelfDays: 5 },
  { name: "Muffins", category: "Bread & Bakery", unit: "unit", estimatedShelfDays: 5 },
  { name: "Naan", category: "Bread & Bakery", unit: "unit", estimatedShelfDays: 7 },
  { name: "Pita Bread", category: "Bread & Bakery", unit: "unit", estimatedShelfDays: 7 },
  { name: "Sourdough Loaf", category: "Bread & Bakery", unit: "unit", estimatedShelfDays: 5 },
  { name: "Tortillas", category: "Bread & Bakery", unit: "unit", estimatedShelfDays: 14 },
  { name: "Whole Wheat Bread", category: "Bread & Bakery", unit: "unit", estimatedShelfDays: 7 },
  // --- Bulk & Dry (24 items) ---
  { name: "Brown Rice", category: "Grains & Pasta", unit: "lb", estimatedShelfDays: 365 },
  { name: "Bulk Almonds", category: "Snacks", unit: "lb", estimatedShelfDays: 365 },
  { name: "Bulk Cashews", category: "Snacks", unit: "lb", estimatedShelfDays: 180 },
  { name: "Bulk Pecans", category: "Snacks", unit: "lb", estimatedShelfDays: 180 },
  { name: "Bulk Peanuts", category: "Snacks", unit: "lb", estimatedShelfDays: 365 },
  { name: "Bulk Walnuts", category: "Snacks", unit: "lb", estimatedShelfDays: 180 },
  { name: "Chia Seeds", category: "Snacks", unit: "lb", estimatedShelfDays: 730 },
  { name: "Coffee Beans", category: "Beverages", unit: "lb", estimatedShelfDays: 30 },
  { name: "Dried Apricots", category: "Snacks", unit: "oz", estimatedShelfDays: 365 },
  { name: "Dried Black Beans", category: "Grains & Pasta", unit: "lb", estimatedShelfDays: 1825 },
  { name: "Dried Chickpeas", category: "Grains & Pasta", unit: "lb", estimatedShelfDays: 1825 },
  { name: "Dried Cranberries", category: "Snacks", unit: "oz", estimatedShelfDays: 365 },
  { name: "Dried Kidney Beans", category: "Grains & Pasta", unit: "lb", estimatedShelfDays: 1825 },
  { name: "Dried Lentils", category: "Grains & Pasta", unit: "lb", estimatedShelfDays: 1825 },
  { name: "Dried Mango", category: "Snacks", unit: "oz", estimatedShelfDays: 365 },
  { name: "Flaxseed", category: "Snacks", unit: "lb", estimatedShelfDays: 365 },
  { name: "Granola", category: "Breakfast & Cereal", unit: "lb", estimatedShelfDays: 90 },
  { name: "Loose Leaf Tea", category: "Beverages", unit: "oz", estimatedShelfDays: 365 },
  { name: "Pumpkin Seeds", category: "Snacks", unit: "lb", estimatedShelfDays: 365 },
  { name: "Quinoa", category: "Grains & Pasta", unit: "lb", estimatedShelfDays: 730 },
  { name: "Rolled Oats", category: "Breakfast & Cereal", unit: "lb", estimatedShelfDays: 730 },
  { name: "Steel Cut Oats", category: "Breakfast & Cereal", unit: "lb", estimatedShelfDays: 730 },
  { name: "Sunflower Seeds", category: "Snacks", unit: "lb", estimatedShelfDays: 365 },
  { name: "White Rice", category: "Grains & Pasta", unit: "lb", estimatedShelfDays: 1825 },
  // --- Deli Cheese (3 items) ---
  { name: "Deli Cheddar", category: "Dairy", unit: "lb", estimatedShelfDays: 14 },
  { name: "Deli Provolone", category: "Dairy", unit: "lb", estimatedShelfDays: 14 },
  { name: "Deli Swiss Cheese", category: "Dairy", unit: "lb", estimatedShelfDays: 14 },
  // --- Breakfast & Cereal (10 items) ---
  {
    name: "Breakfast Cereal",
    category: "Breakfast & Cereal",
    unit: "box",
    estimatedShelfDays: 180,
  },
  { name: "Corn Flakes", category: "Breakfast & Cereal", unit: "box", estimatedShelfDays: 180 },
  { name: "Granola Bars", category: "Breakfast & Cereal", unit: "box", estimatedShelfDays: 180 },
  { name: "Instant Oatmeal", category: "Breakfast & Cereal", unit: "box", estimatedShelfDays: 365 },
  { name: "Maple Syrup", category: "Breakfast & Cereal", unit: "fl oz", estimatedShelfDays: 365 },
  { name: "Muesli", category: "Breakfast & Cereal", unit: "lb", estimatedShelfDays: 180 },
  { name: "Pancake Mix", category: "Breakfast & Cereal", unit: "lb", estimatedShelfDays: 270 },
  { name: "Pancake Syrup", category: "Breakfast & Cereal", unit: "fl oz", estimatedShelfDays: 365 },
  { name: "Pop-Tarts", category: "Breakfast & Cereal", unit: "box", estimatedShelfDays: 180 },
  { name: "Protein Bars", category: "Breakfast & Cereal", unit: "box", estimatedShelfDays: 180 },
  // --- Baking (12 items) ---
  { name: "All-Purpose Flour", category: "Baking", unit: "lb", estimatedShelfDays: 365 },
  { name: "Baking Powder", category: "Baking", unit: "oz", estimatedShelfDays: 365 },
  { name: "Baking Soda", category: "Baking", unit: "oz", estimatedShelfDays: 730 },
  { name: "Brown Sugar", category: "Baking", unit: "lb", estimatedShelfDays: 730 },
  { name: "Chocolate Chips", category: "Baking", unit: "oz", estimatedShelfDays: 365 },
  { name: "Cocoa Powder", category: "Baking", unit: "oz", estimatedShelfDays: 365 },
  { name: "Cornstarch", category: "Baking", unit: "oz", estimatedShelfDays: 1095 },
  { name: "Honey", category: "Baking", unit: "fl oz", estimatedShelfDays: 1825 },
  { name: "Powdered Sugar", category: "Baking", unit: "lb", estimatedShelfDays: 730 },
  { name: "Vanilla Extract", category: "Baking", unit: "fl oz", estimatedShelfDays: 1095 },
  { name: "White Sugar", category: "Baking", unit: "lb", estimatedShelfDays: 730 },
  { name: "Whole Wheat Flour", category: "Baking", unit: "lb", estimatedShelfDays: 180 },
  // --- Oils & Vinegars (8 items) ---
  {
    name: "Apple Cider Vinegar",
    category: "Oils & Vinegars",
    unit: "fl oz",
    estimatedShelfDays: 1825,
  },
  {
    name: "Balsamic Vinegar",
    category: "Oils & Vinegars",
    unit: "fl oz",
    estimatedShelfDays: 1825,
  },
  { name: "Canola Oil", category: "Oils & Vinegars", unit: "fl oz", estimatedShelfDays: 365 },
  { name: "Coconut Oil", category: "Oils & Vinegars", unit: "fl oz", estimatedShelfDays: 730 },
  { name: "Cooking Spray", category: "Oils & Vinegars", unit: "unit", estimatedShelfDays: 365 },
  {
    name: "Extra Virgin Olive Oil",
    category: "Oils & Vinegars",
    unit: "fl oz",
    estimatedShelfDays: 365,
  },
  {
    name: "Red Wine Vinegar",
    category: "Oils & Vinegars",
    unit: "fl oz",
    estimatedShelfDays: 1825,
  },
  { name: "Vegetable Oil", category: "Oils & Vinegars", unit: "fl oz", estimatedShelfDays: 365 },
] as const;
